In [ ]:
import pandas as pd
df = pd.read_csv('heart.csv')
df.head()

    age  anaemia  creatinine_phosphokinase  ...  smoking  time  DEATH_EVENT
0  75.0        0                       582  ...        0     4            1
1  55.0        0                      7861  ...        0     6            1
2  65.0        0                       146  ...        1     7            1
3  50.0        1                       111  ...        0     7            1
4  65.0        1                       160  ...        0     8            1

[5 rows x 13 columns]

In [ ]:
df['DEATH_EVENT'].value_counts()

0    203
1     96
Name: DEATH_EVENT, dtype: int64

In [ ]:
df.isnull().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [ ]:
df.describe()

              age     anaemia  ...        time  DEATH_EVENT
count  299.000000  299.000000  ...  299.000000    299.00000
mean    60.833893    0.431438  ...  130.260870      0.32107
std     11.894809    0.496107  ...   77.614208      0.46767
min     40.000000    0.000000  ...    4.000000      0.00000
25%     51.000000    0.000000  ...   73.000000      0.00000
50%     60.000000    0.000000  ...  115.000000      0.00000
75%     70.000000    1.000000  ...  203.000000      1.00000
max     95.000000    1.000000  ...  285.000000      1.00000

[8 rows x 13 columns]

In [ ]:
X = df.drop('DEATH_EVENT',axis=1).values
Y = df[['DEATH_EVENT']].values

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,Y)

In [ ]:
from sklearn.svm import SVC
smodel1 = SVC(C=1.0, kernel='linear')

smodel1.fit(xtrain,ytrain)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
print(smodel1.score(xtrain,ytrain))
print(smodel1.score(xtest,ytest))

0.7633928571428571
0.8266666666666667

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(ytest,smodel1.predict(xtest))

array([[49,  6],
       [ 7, 13]])

#Polynomial SVM Kernel

In [ ]:
from sklearn.svm import SVC
smodel2 = SVC(C=2.0, kernel='poly' , degree=4)

smodel2.fit(xtrain,ytrain)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(C=2.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=4, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
print(smodel2.score(xtrain,ytrain))
print(smodel2.score(xtest,ytest))

0.6607142857142857
0.7333333333333333

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(ytest,smodel2.predict(xtest))

array([[55,  0],
       [20,  0]])

#RBF kernel

In [ ]:
from sklearn.svm import SVC
smodel3 = SVC(C=2.0, kernel='rbf',degree=5)

smodel3.fit(xtrain,ytrain)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(C=2.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=5, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
print(smodel3.score(xtrain,ytrain))
print(smodel3.score(xtest,ytest))

0.6607142857142857
0.7333333333333333

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(ytest,smodel3.predict(xtest))

array([[55,  0],
       [20,  0]])

#On Applying SVM on the following data find out which kernel gives best accurate model

In [ ]:
from sklearn.datasets import load_breast_cancer
df = load_breast_cancer()

In [ ]:
df.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [ ]:
import pandas as pd
X = pd.DataFrame(df['data'],columns=df['feature_names'])
Y = df['target']

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,Y)

In [ ]:
from sklearn.svm import SVC
smodel_c = SVC(C=1.0, kernel='linear')

smodel_c.fit(xtrain,ytrain)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
print(smodel_c.score(xtrain,ytrain))
print(smodel_c.score(xtest,ytest))

0.9694835680751174
0.951048951048951

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(ytest,smodel_c.predict(xtest))

array([[59,  6],
       [ 1, 77]])